name: buffer
description: >
  Utility functions and classes to work with byte buffers and streams efficiently,
  to read and write binary data formats.
version: 1.0.2
homepage: https://github.com/isoos/buffer
author: Istvan Soos <istvan.soos@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^1.0.0
